apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-{{ .Values.namespace }}-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT