appName: myapp-backend
namespace: default
healthCheckPath: /health
ingressAnnotations:
  backendConfig: '{"default": "{{ .Values.appName }}-{{ .Values.namespace }}" }'
replica: 1
containerPort: 8080
containerImage: michelesm/myapp:latest
staticIpName: myApp-development #For GKE cluster
certMapName: myApp-wildcard-map # Certificate
envars: 
  -
    name: "FLASK_APP"
    value: "/app/server.py"
  -
    name: "FLASK_ENV"
    value: "development"
  -
    name: "MYSQL_HOST"
    value: "myapp-db.default.svc.cluster.local"
  -
    name: "MYSQL_ROOT_PASSWORD"
    value: "myapp321"
  -
    name: "MYSQL_USER"
    value: "root"
  -
    name: "MYSQL_DATABASE"
    value: "myapp"